nav:
  - name: <span class="important">Winners</span>
    url: /winners
  - name: Rules
    url: /rules
  - name: Judges
    url: /judges
  - name: Sponsors
    url: /sponsors
  - name: Prizes
    url: /prizes
  - name: Contact
    url: /#contact

platinum_sponsor:
  name: PegB
  image: pegb.svg
  logo: pegb_logo.svg
  url: https://www.pegb.tech/
  description: Secure Cashless Payments for everyone, everywhere
  background_color: "#f05323"

gold_sponsors:
  - name: AdRoll
    image: droll.svg
    logo: droll.png
    url: https://www.adroll.com/
    description: The retargeting and prospecting platform of choice for over 35,000 advertisers worldwide
    background_color: "#00aeef"
  - name: Alert Logic
    image: alertlogic.svg
    logo: alertlogic.png
    url: https://www.alertlogic.com/
    description: Security as a Service
    background_color: "#ff7e00"
  - name: BairesDev
    image: bairesdev.svg
    logo: bairesdev.png
    url: https://www.bairesdev.com/
    description: "Leaders in Staff Augmentation: The extra talent needed to boost your projects"
    background_color: "#1774b3"
  - name: Erlang Solutions
    image: esl.svg
    logo: esl.png
    url: https://www.erlang-solutions.com/
    description: "Erlang, Elixir & BEAM Technology Consultancy"
    background_color: "#ab191e"

prizes:
  - name: <strong>900USD</strong> Free 2-day CodeBEAM SF ticket
    sponsor: Erlang Solutions
    sponsor_url: https://www.erlang-solutions.com/
    url: http://www.erlang-factory.com/codebeamsf2018/
    image: codebeamsf2018.jpg
  - name: <strong>500USD</strong> Amazon Gift Card
    sponsor: PegB
    sponsor_url: https://www.pegb.tech/
    url: https://www.amazon.com/gift-cards/
    image: amazon-gift-card-500.png
  - name: <strong>500USD</strong> Amazon Gift Card
    sponsor: PegB
    sponsor_url: https://www.pegb.tech/
    url: https://www.amazon.com/gift-cards/
    image: amazon-gift-card-500.png
  - name: <strong>500USD</strong> Amazon Gift Card
    sponsor: PegB
    sponsor_url: https://www.pegb.tech/
    url: https://www.amazon.com/gift-cards/
    image: amazon-gift-card-500.png
  - name: <strong>600USD</strong> ThinkGeek Gift Card
    sponsor: BairesDev
    sponsor_url: https://www.bairesdev.com/
    url: https://www.thinkgeek.com/brain/order/certificate.cgi
    image: thinkgeek-gift-card.jpg
  - name: <strong>500USD</strong> Gyft Card
    sponsor: Alert Logic
    sponsor_url: https://www.alertlogic.com/
    url: https://www.gyft.com/buy-gift-cards/gyft-card/?category=Featured%20Gift%20Cards
    image: gyft-card2.png
  - name: <strong>400USD</strong> Free ticket to Any CodeBEAM Lite
    sponsor: Erlang Solutions
    sponsor_url: https://www.erlang-solutions.com/
    url: http://www.erlang-factory.com
    image: codebeamlite2018.jpg
  - name: <strong>300USD</strong> Sparkfun Gift Card
    sponsor: AdRoll
    sponsor_url: https://www.adroll.com/
    url: https://www.sparkfun.com/products/13726
    image: sparkfun-gift-certificate.jpg
  - name: <strong>300USD</strong> Amazon Gift Card
    sponsor: AdRoll
    sponsor_url: https://www.adroll.com/
    url: https://www.amazon.com/gift-cards/
    image: amazon-gift-card5.png

judges:
  - name: Fred Hebert
    url: https://ferd.ca/
    twitter: mononcqc
    image: fred.jpg
  - name: Joe Armstrong
    url: https://joearms.github.io/
    twitter: joeerl
    image: joe.jpg
  - name: Christopher Meiklejohn
    url: http://christophermeiklejohn.com/
    twitter: cmeik
    image: chris.jpeg
  - name: René Föhring
    url: http://trivelop.de/
    twitter: rrrene
    image: rrrene.png
  - name: Marcelo Gornstein
    url: https://marcelog.github.io/
    twitter: mgornstein
    image: chelo.jpeg
  - name: Robert Virding
    url: http://rvirding.blogspot.com.ar/
    twitter: rvirding
    image: rvirding.png

winner:
  team: ElixirChain
  project: ElixirBench
  repo: elixirbench
  description: A service to maintain long running benchmarks for Elixir projects.
  link: https://www.elixirbench.org/
  members:
    - name: Michał Muskała
      user: michalmuskala
      avatar: https://avatars0.githubusercontent.com/u/477062
    - name: Andrew Dryga
      user: AndrewDryga
      avatar: https://avatars0.githubusercontent.com/u/1877644
    - name: Alexey Bondarenko
      user: alexeybondarenko
      avatar: https://avatars1.githubusercontent.com/u/3592553
  prizes:
    - name: <strong>900USD</strong> Free 2-day CodeBEAM SF ticket
      sponsor: Erlang Solutions
      sponsor_url: https://www.erlang-solutions.com/
      url: http://www.erlang-factory.com/codebeamsf2018/
      image: codebeamsf2018.jpg
    - name: <strong>500USD</strong> Amazon Gift Card
      sponsor: PegB
      sponsor_url: https://www.pegb.tech/
      url: https://www.amazon.com/gift-cards/
      image: amazon-gift-card-500.png
  comments:
    - text: This could be very useful for the community
      author: Robert, René, Fred, Chelo
    - text: Surprising amount of work done
      author: Fred

category_winners:
  - team: weLaika
    project: Sputnik
    repo: sputnik
    description: A website crawler written in Elixir (Crawling since 1957)
    link: https://spawnfest.github.io/sputnik/Sputnik.html
    category: Completion
    members:
      - name: Riccardo Magliocchetti
        user: xrmx
        avatar: https://avatars3.githubusercontent.com/u/12932
      - name: Fabrizio Monti
        user: delphaber
        avatar: https://avatars2.githubusercontent.com/u/139284
      - name: Filippo Gangi Dino
        user: mukkoo
        avatar: https://avatars0.githubusercontent.com/u/1052512
      - name: Stefano Pau
        user: ramensoup
        avatar: https://avatars0.githubusercontent.com/u/9130232
    prize:
      name: <strong>500USD</strong> Amazon Gift Card
      sponsor: PegB
      sponsor_url: https://www.pegb.tech/
      url: https://www.amazon.com/gift-cards/
      image: amazon-gift-card-500.png
    comments:
      - text: Nicely documented; Good UI; Extra points for good accessibility.
        author: René
      - text: Nice ASCII art, useful to find dead links.
        author: Fred
  - team: "0xfafafa"
    project: Flock
    repo: flock
    description: Flock is a lightweight process registry and forgiving supervisor library for Erlang/Elixir applications.
    link: https://spawnfest.github.io/flock/Flock.html
    category: Maintainability
    members:
      - name: Ricardo Lanziano
        user: arpunk
        avatar: https://avatars3.githubusercontent.com/u/11342
      - name: Cristian Rosa
        user: rosacris
        avatar: https://avatars3.githubusercontent.com/u/697234
      - name: Germán Botto
        user: germanbotto
        avatar: https://avatars0.githubusercontent.com/u/5189728
      - name: Federico Bergero
        user: fbergero
        avatar: https://avatars1.githubusercontent.com/u/8310634
    prize:
      name: <strong>500USD</strong> Gyft Card
      sponsor: Alert Logic
      sponsor_url: https://www.alertlogic.com/
      url: https://www.gyft.com/buy-gift-cards/gyft-card/?category=Featured%20Gift%20Cards
      image: gyft-card2.png
    comments:
      - text: Decent docs, tests pass. The process registry idea is not new, but the CRDT approach here is fun.
        author: Fred
      - text: Extra points for including and running dialyzer!
        author: Chelo
  - team: Fluid Views Tribune
    project: Stories Evolved
    repo: fluid_views_tribune
    description: A completely unnecessary evolution based story generator.
    category: Correctness
    members:
      - name: James Edward Gray II
        user: JEG2
        avatar: https://avatars1.githubusercontent.com/u/5639
      - name: Paul Dawson
        user: piisalie
        avatar: https://avatars3.githubusercontent.com/u/3163390
    prize:
      name: <strong>600USD</strong> ThinkGeek Gift Card
      sponsor: BairesDev
      sponsor_url: https://www.bairesdev.com/
      url: https://www.thinkgeek.com/brain/order/certificate.cgi
      image: thinkgeek-gift-card.jpg
    comments:
      - text: I like the simulation-first approach; code is clean and structured; bonus points for terminal-size-dependant ASCII animations.
        author: René
      - text: Nice simulation, nice use of processes, nice display.  All around nice work.
        author: Chris
  - team: NEPI
    project: Nobody Expects Polish Inquisition
    repo: nepi
    description: It provides sensors based on Nerves to help automate flower growing process. All data can be checked in realtime on web app based on Phoenix.
    link: https://twitter.com/Dreat_/status/939890791115296768
    category: Innovation
    members:
      - name: Arkadiusz Plichta
        user: elpikel
        avatar: https://avatars0.githubusercontent.com/u/29837
      - name: Filip Małachowicz
        user: Exef
        avatar: https://avatars3.githubusercontent.com/u/1412001
      - name: Łukasz Skotarek
        user: Dreat
        avatar: https://avatars2.githubusercontent.com/u/3110673
      - name: Maciej Rylko
        user: rylek90
        avatar: https://avatars0.githubusercontent.com/u/10184544
    prize:
      name: <strong>500USD</strong> Amazon Gift Card
      sponsor: PegB
      sponsor_url: https://www.pegb.tech/
      url: https://www.amazon.com/gift-cards/
      image: amazon-gift-card-500.png
    comments:
      - text: Bonus points for README illustrations.
        author: René
      - text: Nice mix of techs!! :)
        author: Chelo
  - team: Around25 IMAP
    project: Eximap
    repo: around25-imap
    description: Eximap is an elixir library that can connect to IMAP servers via TLS and execute commands.
    category: Usefulness
    members:
      - name: Cosmin Harangus
        user: cosmin-harangus
        avatar: https://avatars2.githubusercontent.com/u/381639
    prize:
      name: <strong>400USD</strong> Free ticket to Any CodeBEAM Lite
      sponsor: Erlang Solutions
      sponsor_url: https://www.erlang-solutions.com/
      url: http://www.erlang-factory.com
      image: codebeamlite2018.jpg
    comments:
      - text: While not a novel technology, creating an IMAP lib in Elixir is a great idea.
        author: Robert
      - text: Excited to see IMAP support around.
        author: Fred, Chris
  - team: Erisata
    project: FireFork
    repo: fire-fork
    description: This is an application for launching fireworks remotely.
    category: Creativity
    members:
      - name: Karolis Petrauskas
        user: kape1395
        avatar: https://avatars3.githubusercontent.com/u/442726
      - name: Donatas
        user: DonHub
        avatar: https://avatars0.githubusercontent.com/u/3988116
      - name: Kazimieras Senvaitis
        user: Eseas
        avatar: https://avatars0.githubusercontent.com/u/19321727
    prize:
      name: <strong>300USD</strong> Sparkfun Gift Card
      sponsor: AdRoll
      sponsor_url: https://www.adroll.com/
      url: https://www.sparkfun.com/products/13726
      image: sparkfun-gift-certificate.jpg
    comments:
      - text: Very cool concept, but hard to test -- actually has a working Wx GUI though, so props for that.
        author: Fred
      - text: Cool idea -- I had a friend who was touring trying to do similar things with Erlang and sync'ing audio and video streams.
        author: Chris
  - team: Lagom
    project: lagom
    repo: lagom
    description: A robot that really listens what you have to say (in English).
    link: https://lagom.facorro.com/
    category: Creativity
    members:
      - name: Juan Facorro
        user: jfacorro
        avatar: https://avatars3.githubusercontent.com/u/1522569
    prize:
      name: <strong>300USD</strong> Amazon Gift Card
      sponsor: AdRoll
      sponsor_url: https://www.adroll.com/
      url: https://www.amazon.com/gift-cards/
      image: amazon-gift-card5.png
    comments:
      - text: Clojerl! Nice choice. Instructions were clear and the concept cool.
        author: Fred
      - text: Extra points for using clojerl in an ambitious project, leaving an online demo, and also packing everything into a nice docker image.
        author: Chelo

rules:
  - text: "Schedule"
    details:
      - text: The event will start on <strong>2017-12-09 00:00 UTC</strong>.
      - text: The event will end on <strong>2017-12-10 23:59 UTC</strong>.
      - text: The registration will close <span class="line-through">2 days</span> 1 day prior to the start date.
      - text: Each team will have exactly 48 hours to work on their projects.
  - text: Teams
    details:
      - text: "Team size is 1 to 4."
      - text: "Every team member has to be a human being, not an organization."
      - text: "All members of the team should be 13 years old or older."
      - text: "Judges of this contest can not participate in it as members of a team."
      - text: Every team has to be registered by completing the <a target="_blank" href="https://goo.gl/forms/kCY0ekjqZI6PPZRl2">registration form</a>.
  - text: Projects
    details:
      - text: "All projects should be written to run on the Erlang VM / BEAM."
      - text: "They can be written in any BEAM-based language (i.e. Erlang, Elixir, LFE, efene, clojerl, etc.)."
      - text: "Supplementary languages such as Javascript (and JS frameworks) are allowed."
      - text: "No code can be created before the start of the contest."
      - text: Each team should come up with their own project idea (If you need inspiration check <a target="_blank" href="https://appideagenerator.com/">this website</a>)
      - text: "The organizing team will create a git repository at GitHub for each team."
      - text: "If a team needs more than one, they can ask the organizers to create extra repos for them."
      - text: "All deliverables should be uploaded to the repository, which is what will be used by the jury to evaluate the projects."
      - text: "The only required deliverable is the code, but everything in the repository will be used for evaluation."
      - text: "Suggested extra deliverables to include: Documentation, comprehensive README.md, project-related art (e.g. Logos), tests and anything that makes building and understanding the system easier for the judges."
      - text: "Usage of third party libraries and web services is not prohibited, even encouraged."
      - text: "<em>Ownership and Copyright:</em> Each team retains all the rights to their submissions."
      - text: "<em>User Privacy:</em> If a project is an online application (such as a web application) that collects personal information from its users, it should not reveal any of personally identifiable information unless required to do so by law. Please respect people&#8217;s privacy."
      - text: "Lawful submissions only: please do not submit anything that can be considered harmful, unlawful or both."
  - text: Evaluation
    details:
      - text: "Your work will be judged by a publicly known jury, unless previously disqualified."
      - text: "Each sponsor is responsible for delivering the prize they provided to the corresponding winning team."
      - text: "Each project will be evaluated in 6 different categories: Creativity, Usefulness, Innovation, Correctness, Maintainability and Completion."
      - text: "Final interpretation of each category meaning is up to the judges, but as general guidelines:
              <dl>
                <dt>Creativity</dt><dd>This category assigns points for unexpectedness, eccentricity, fun. This is a broad category that may apply to the project, its code, the team, etc.</dd>
                <dt>Usefulness</dt><dd>How useful the project will be for its target users. Does it solve an existing problem? Does it significantly reduce work time for its users?</dd>
                <dt>Innovation</dt><dd>How groundbreaking the project is. The more unique and unprecedented the idea behind the project, the better. Also applies to projects developed in a unique way.</dd>
                <dt>Correctness</dt><dd>The less bugs, the better. This category values working products over complete ones.</dd>
                <dt>Maintainability</dt><dd>How easy will be for future developers to keep contributing to this project after SpawnFest is over.</dd>
                <dt>Completion</dt><dd>Is the project functional? Did the team get to a point where there is something to show, even if there are a few bugs here and there?</dd>
              </dl>
              "
      - text: "Final score of each team will be computed as the sum of the points received in all those categories."
      - text: "The team with the highest final score will be the winner of the contest."
      - text: "Other prizes, besides the one for the winner, will be awarded as well."
  - text: Other Rules
    details:
      - text: "Individual participants or even entire teams can be disqualified if they don't abide by these rules. The organizers reserve the right to apply the punishment they consider fit to any transgression."
      - text: "Event organizers will not reimburse you for any expenses or losses."
      - text: "Event organizers are not responsible for any damage, legal actions or any other outcomes that might be a result of your participation."
      - text: "Event organizers reserve the right to change these rules without prior notification."
